export const GET_PAYMENTS_RESPONSE = 'GET_PAYMENTS_RESPONSE';
export const GET_PAYMENT_RESPONSE = 'GET_PAYMENT_RESPONSE';
export const ADD_NEW_PAYMENT_RESPONSE = 'ADD_NEW_PAYMENT_RESPONSE';
export const UPDATE_EXISTING_PAYMENT_RESPONSE = 'UPDATE_EXISTING_PAYMENT_RESPONSE';
export const DELETE_PAYMENT_RESPONSE = 'DELETE_PAYMENT_RESPONSE';

export const API_CALL_BEGIN = 'API_CALL_BEGIN';
export const API_CALL_ERROR = 'API_CALL_ERROR';
